### PR TITLE
trim license header to appease fmt-maven-plugin

### PR DESCRIPTION
**Pull request by danielnorberg**

### CODE REVIEW

**Comment by danielnorberg** [comment]
I believe this resolves #5 but needs verification

**Review by mattnworb — APPROVED** [review]
would you mind testing this by doing `mvn install` to install a snapshot and then using it in some other repo like logging-java? (unless you already have)

**Comment by danielnorberg** [comment]
@mattnworb successfully tried it with logging-java: https://github.com/spotify/logging-java/commit/c4322fd1c622aa5ed7444a0a2c62d9418a676384

"Works on my laptop" but build fails in CI of course because of lack of foss-root snapshot.

**Comment by danielnorberg** [comment]
🙏

**Pull request merged**
